// <auto-generated />
namespace DevJobs.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AdditionalPropertiesAddedToModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdditionalPropertiesAddedToModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201710101547090_AdditionalPropertiesAddedToModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
